// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: addresses.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAddressTxsByTxid = `-- name: DeleteAddressTxsByTxid :exec
DELETE FROM address_txs WHERE txid = $1
`

func (q *Queries) DeleteAddressTxsByTxid(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteAddressTxsByTxid, txid)
	return err
}

const getAddressBalance = `-- name: GetAddressBalance :one
SELECT address, balance, received, sent, txs, updated_at FROM address_balance WHERE address = $1
`

func (q *Queries) GetAddressBalance(ctx context.Context, address string) (AddressBalance, error) {
	row := q.db.QueryRow(ctx, getAddressBalance, address)
	var i AddressBalance
	err := row.Scan(
		&i.Address,
		&i.Balance,
		&i.Received,
		&i.Sent,
		&i.Txs,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressTxs = `-- name: GetAddressTxs :many
SELECT t.txid, t.hash, t.block_hash, t.block_height, t.block_time, t.size, t.vsize, t.version, t.locktime, t.coinbase, t.created_at, a.tx_type, a.block_height, a.block_time
FROM address_txs a
JOIN transactions t ON t.txid = a.txid
WHERE a.address = $1
ORDER BY a.block_height DESC
LIMIT $2 OFFSET $3
`

type GetAddressTxsParams struct {
	Address string
	Limit   int32
	Offset  int32
}

type GetAddressTxsRow struct {
	Txid          string
	Hash          string
	BlockHash     string
	BlockHeight   int64
	BlockTime     int64
	Size          int64
	Vsize         int64
	Version       int64
	Locktime      int64
	Coinbase      bool
	CreatedAt     pgtype.Timestamptz
	TxType        string
	BlockHeight_2 int64
	BlockTime_2   int64
}

func (q *Queries) GetAddressTxs(ctx context.Context, arg GetAddressTxsParams) ([]GetAddressTxsRow, error) {
	rows, err := q.db.Query(ctx, getAddressTxs, arg.Address, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAddressTxsRow
	for rows.Next() {
		var i GetAddressTxsRow
		if err := rows.Scan(
			&i.Txid,
			&i.Hash,
			&i.BlockHash,
			&i.BlockHeight,
			&i.BlockTime,
			&i.Size,
			&i.Vsize,
			&i.Version,
			&i.Locktime,
			&i.Coinbase,
			&i.CreatedAt,
			&i.TxType,
			&i.BlockHeight_2,
			&i.BlockTime_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAddressBalance = `-- name: IncrementAddressBalance :exec
INSERT INTO address_balance (address, balance, received, sent, txs, updated_at)
VALUES ($1, $2, $3, $4, 1, NOW())
ON CONFLICT (address) DO UPDATE SET
    balance    = address_balance.balance + EXCLUDED.balance,
    received   = address_balance.received + EXCLUDED.received,
    sent       = address_balance.sent + EXCLUDED.sent,
    txs        = address_balance.txs + 1,
    updated_at = NOW()
`

type IncrementAddressBalanceParams struct {
	Address  string
	Balance  int64
	Received int64
	Sent     int64
}

func (q *Queries) IncrementAddressBalance(ctx context.Context, arg IncrementAddressBalanceParams) error {
	_, err := q.db.Exec(ctx, incrementAddressBalance,
		arg.Address,
		arg.Balance,
		arg.Received,
		arg.Sent,
	)
	return err
}

const insertAddressTx = `-- name: InsertAddressTx :exec
INSERT INTO address_txs (address, txid, block_height, block_time, tx_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (address, txid) DO NOTHING
`

type InsertAddressTxParams struct {
	Address     string
	Txid        string
	BlockHeight int64
	BlockTime   int64
	TxType      string
}

func (q *Queries) InsertAddressTx(ctx context.Context, arg InsertAddressTxParams) error {
	_, err := q.db.Exec(ctx, insertAddressTx,
		arg.Address,
		arg.Txid,
		arg.BlockHeight,
		arg.BlockTime,
		arg.TxType,
	)
	return err
}

const upsertAddressBalance = `-- name: UpsertAddressBalance :exec
INSERT INTO address_balance (address, balance, received, sent, txs, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (address) DO UPDATE SET
    balance    = EXCLUDED.balance,
    received   = EXCLUDED.received,
    sent       = EXCLUDED.sent,
    txs        = EXCLUDED.txs,
    updated_at = NOW()
`

type UpsertAddressBalanceParams struct {
	Address  string
	Balance  int64
	Received int64
	Sent     int64
	Txs      int64
}

func (q *Queries) UpsertAddressBalance(ctx context.Context, arg UpsertAddressBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertAddressBalance,
		arg.Address,
		arg.Balance,
		arg.Received,
		arg.Sent,
		arg.Txs,
	)
	return err
}
