// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blocks.sql

package repository

import (
	"context"
)

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE hash = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteBlock, hash)
	return err
}

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT hash, height, prev_hash, merkle_root, time, bits, nonce, size, weight, version, difficulty, chainwork, tx_count, created_at FROM blocks WHERE hash = $1
`

func (q *Queries) GetBlockByHash(ctx context.Context, hash string) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, hash)
	var i Block
	err := row.Scan(
		&i.Hash,
		&i.Height,
		&i.PrevHash,
		&i.MerkleRoot,
		&i.Time,
		&i.Bits,
		&i.Nonce,
		&i.Size,
		&i.Weight,
		&i.Version,
		&i.Difficulty,
		&i.Chainwork,
		&i.TxCount,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockByHeight = `-- name: GetBlockByHeight :one
SELECT hash, height, prev_hash, merkle_root, time, bits, nonce, size, weight, version, difficulty, chainwork, tx_count, created_at FROM blocks WHERE height = $1
`

func (q *Queries) GetBlockByHeight(ctx context.Context, height int64) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHeight, height)
	var i Block
	err := row.Scan(
		&i.Hash,
		&i.Height,
		&i.PrevHash,
		&i.MerkleRoot,
		&i.Time,
		&i.Bits,
		&i.Nonce,
		&i.Size,
		&i.Weight,
		&i.Version,
		&i.Difficulty,
		&i.Chainwork,
		&i.TxCount,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockHashByHeight = `-- name: GetBlockHashByHeight :one
SELECT hash FROM blocks WHERE height = $1
`

func (q *Queries) GetBlockHashByHeight(ctx context.Context, height int64) (string, error) {
	row := q.db.QueryRow(ctx, getBlockHashByHeight, height)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const getBlockHeightByHash = `-- name: GetBlockHeightByHash :one
SELECT height FROM blocks WHERE hash = $1
`

func (q *Queries) GetBlockHeightByHash(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRow(ctx, getBlockHeightByHash, hash)
	var height int64
	err := row.Scan(&height)
	return height, err
}

const getLatestBlockHeight = `-- name: GetLatestBlockHeight :one
SELECT COALESCE(MAX(height), 0) FROM blocks
`

func (q *Queries) GetLatestBlockHeight(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestBlockHeight)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getLatestBlocks = `-- name: GetLatestBlocks :many
SELECT hash, height, prev_hash, merkle_root, time, bits, nonce, size, weight, version, difficulty, chainwork, tx_count, created_at FROM blocks ORDER BY height DESC LIMIT $1 OFFSET $2
`

type GetLatestBlocksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetLatestBlocks(ctx context.Context, arg GetLatestBlocksParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, getLatestBlocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Hash,
			&i.Height,
			&i.PrevHash,
			&i.MerkleRoot,
			&i.Time,
			&i.Bits,
			&i.Nonce,
			&i.Size,
			&i.Weight,
			&i.Version,
			&i.Difficulty,
			&i.Chainwork,
			&i.TxCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (hash, height, prev_hash, merkle_root, time, bits, nonce, size, weight, version, difficulty, chainwork, tx_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertBlockParams struct {
	Hash       string
	Height     int64
	PrevHash   string
	MerkleRoot string
	Time       int64
	Bits       string
	Nonce      int64
	Size       int64
	Weight     int64
	Version    int64
	Difficulty float64
	Chainwork  string
	TxCount    int64
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.Hash,
		arg.Height,
		arg.PrevHash,
		arg.MerkleRoot,
		arg.Time,
		arg.Bits,
		arg.Nonce,
		arg.Size,
		arg.Weight,
		arg.Version,
		arg.Difficulty,
		arg.Chainwork,
		arg.TxCount,
	)
	return err
}
