// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chain_state.sql

package repository

import (
	"context"
)

const getChainState = `-- name: GetChainState :one
SELECT key, value FROM chain_state WHERE key = $1
`

func (q *Queries) GetChainState(ctx context.Context, key string) (ChainState, error) {
	row := q.db.QueryRow(ctx, getChainState, key)
	var i ChainState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const setChainState = `-- name: SetChainState :exec
INSERT INTO chain_state (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetChainStateParams struct {
	Key   string
	Value string
}

func (q *Queries) SetChainState(ctx context.Context, arg SetChainStateParams) error {
	_, err := q.db.Exec(ctx, setChainState, arg.Key, arg.Value)
	return err
}
