// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mempool.sql

package repository

import (
	"context"
)

const deleteAllMempool = `-- name: DeleteAllMempool :exec
DELETE FROM mempool
`

func (q *Queries) DeleteAllMempool(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllMempool)
	return err
}

const deleteMempoolTx = `-- name: DeleteMempoolTx :exec
DELETE FROM mempool WHERE txid = $1
`

func (q *Queries) DeleteMempoolTx(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteMempoolTx, txid)
	return err
}

const getMempool = `-- name: GetMempool :many
SELECT txid, time, size, vsize, fee, fee_per_byte FROM mempool ORDER BY time DESC
`

func (q *Queries) GetMempool(ctx context.Context) ([]Mempool, error) {
	rows, err := q.db.Query(ctx, getMempool)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mempool
	for rows.Next() {
		var i Mempool
		if err := rows.Scan(
			&i.Txid,
			&i.Time,
			&i.Size,
			&i.Vsize,
			&i.Fee,
			&i.FeePerByte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMempoolTx = `-- name: GetMempoolTx :one
SELECT txid, time, size, vsize, fee, fee_per_byte FROM mempool WHERE txid = $1
`

func (q *Queries) GetMempoolTx(ctx context.Context, txid string) (Mempool, error) {
	row := q.db.QueryRow(ctx, getMempoolTx, txid)
	var i Mempool
	err := row.Scan(
		&i.Txid,
		&i.Time,
		&i.Size,
		&i.Vsize,
		&i.Fee,
		&i.FeePerByte,
	)
	return i, err
}

const insertMempoolTx = `-- name: InsertMempoolTx :exec
INSERT INTO mempool (txid, time, size, vsize, fee, fee_per_byte)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (txid) DO UPDATE SET
    time         = EXCLUDED.time,
    size         = EXCLUDED.size,
    vsize        = EXCLUDED.vsize,
    fee          = EXCLUDED.fee,
    fee_per_byte = EXCLUDED.fee_per_byte
`

type InsertMempoolTxParams struct {
	Txid       string
	Time       int64
	Size       int64
	Vsize      int64
	Fee        int64
	FeePerByte int64
}

func (q *Queries) InsertMempoolTx(ctx context.Context, arg InsertMempoolTxParams) error {
	_, err := q.db.Exec(ctx, insertMempoolTx,
		arg.Txid,
		arg.Time,
		arg.Size,
		arg.Vsize,
		arg.Fee,
		arg.FeePerByte,
	)
	return err
}
