// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AddressBalance struct {
	Address   string
	Balance   int64
	Received  int64
	Sent      int64
	Txs       int64
	UpdatedAt pgtype.Timestamptz
}

type AddressTx struct {
	Address     string
	Txid        string
	BlockHeight int64
	BlockTime   int64
	TxType      string
}

type Block struct {
	Hash       string
	Height     int64
	PrevHash   string
	MerkleRoot string
	Time       int64
	Bits       string
	Nonce      int64
	Size       int64
	Weight     int64
	Version    int64
	Difficulty float64
	Chainwork  string
	TxCount    int64
	CreatedAt  pgtype.Timestamptz
}

type ChainState struct {
	Key   string
	Value string
}

type Mempool struct {
	Txid       string
	Time       int64
	Size       int64
	Vsize      int64
	Fee        int64
	FeePerByte int64
}

type Transaction struct {
	Txid        string
	Hash        string
	BlockHash   string
	BlockHeight int64
	BlockTime   int64
	Size        int64
	Vsize       int64
	Version     int64
	Locktime    int64
	Coinbase    bool
	CreatedAt   pgtype.Timestamptz
}

type Utxo struct {
	Txid            string
	Vout            int64
	Address         string
	Value           int64
	ScriptPubKeyHex string
	Coinbase        bool
	BlockHeight     int64
}

type Vin struct {
	ID          int64
	Txid        string
	Vout        int64
	Coinbase    string
	PrevTxid    string
	PrevVout    int64
	ScriptSig   string
	Sequence    int64
	Txinwitness []string
}

type Vout struct {
	ID               int64
	Txid             string
	N                int64
	Value            int64
	ScriptPubKeyHex  string
	ScriptPubKeyType string
	Addresses        []string
}
