// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package repository

import (
	"context"
)

const deleteTx = `-- name: DeleteTx :exec
DELETE FROM transactions WHERE txid = $1
`

func (q *Queries) DeleteTx(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteTx, txid)
	return err
}

const deleteTxsByBlockHash = `-- name: DeleteTxsByBlockHash :exec
DELETE FROM transactions WHERE block_hash = $1
`

func (q *Queries) DeleteTxsByBlockHash(ctx context.Context, blockHash string) error {
	_, err := q.db.Exec(ctx, deleteTxsByBlockHash, blockHash)
	return err
}

const getTxByTxid = `-- name: GetTxByTxid :one
SELECT txid, hash, block_hash, block_height, block_time, size, vsize, version, locktime, coinbase, created_at FROM transactions WHERE txid = $1
`

func (q *Queries) GetTxByTxid(ctx context.Context, txid string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTxByTxid, txid)
	var i Transaction
	err := row.Scan(
		&i.Txid,
		&i.Hash,
		&i.BlockHash,
		&i.BlockHeight,
		&i.BlockTime,
		&i.Size,
		&i.Vsize,
		&i.Version,
		&i.Locktime,
		&i.Coinbase,
		&i.CreatedAt,
	)
	return i, err
}

const getTxsByBlockHash = `-- name: GetTxsByBlockHash :many
SELECT txid, hash, block_hash, block_height, block_time, size, vsize, version, locktime, coinbase, created_at FROM transactions WHERE block_hash = $1 ORDER BY block_height DESC
`

func (q *Queries) GetTxsByBlockHash(ctx context.Context, blockHash string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTxsByBlockHash, blockHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.Txid,
			&i.Hash,
			&i.BlockHash,
			&i.BlockHeight,
			&i.BlockTime,
			&i.Size,
			&i.Vsize,
			&i.Version,
			&i.Locktime,
			&i.Coinbase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTxsByBlockHeight = `-- name: GetTxsByBlockHeight :many
SELECT txid, hash, block_hash, block_height, block_time, size, vsize, version, locktime, coinbase, created_at FROM transactions WHERE block_height = $1
`

func (q *Queries) GetTxsByBlockHeight(ctx context.Context, blockHeight int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTxsByBlockHeight, blockHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.Txid,
			&i.Hash,
			&i.BlockHash,
			&i.BlockHeight,
			&i.BlockTime,
			&i.Size,
			&i.Vsize,
			&i.Version,
			&i.Locktime,
			&i.Coinbase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTx = `-- name: InsertTx :exec
INSERT INTO transactions (txid, hash, block_hash, block_height, block_time, size, vsize, version, locktime, coinbase)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTxParams struct {
	Txid        string
	Hash        string
	BlockHash   string
	BlockHeight int64
	BlockTime   int64
	Size        int64
	Vsize       int64
	Version     int64
	Locktime    int64
	Coinbase    bool
}

func (q *Queries) InsertTx(ctx context.Context, arg InsertTxParams) error {
	_, err := q.db.Exec(ctx, insertTx,
		arg.Txid,
		arg.Hash,
		arg.BlockHash,
		arg.BlockHeight,
		arg.BlockTime,
		arg.Size,
		arg.Vsize,
		arg.Version,
		arg.Locktime,
		arg.Coinbase,
	)
	return err
}
