// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: utxos.sql

package repository

import (
	"context"
)

const deleteUtxo = `-- name: DeleteUtxo :exec
DELETE FROM utxos WHERE txid = $1 AND vout = $2
`

type DeleteUtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) DeleteUtxo(ctx context.Context, arg DeleteUtxoParams) error {
	_, err := q.db.Exec(ctx, deleteUtxo, arg.Txid, arg.Vout)
	return err
}

const deleteUtxosByAddress = `-- name: DeleteUtxosByAddress :exec
DELETE FROM utxos WHERE address = $1
`

func (q *Queries) DeleteUtxosByAddress(ctx context.Context, address string) error {
	_, err := q.db.Exec(ctx, deleteUtxosByAddress, address)
	return err
}

const deleteUtxosByTxid = `-- name: DeleteUtxosByTxid :exec
DELETE FROM utxos WHERE txid = $1
`

func (q *Queries) DeleteUtxosByTxid(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteUtxosByTxid, txid)
	return err
}

const getUtxosByAddress = `-- name: GetUtxosByAddress :many
SELECT txid, vout, address, value, script_pub_key_hex, coinbase, block_height FROM utxos WHERE address = $1 ORDER BY block_height DESC, vout
`

func (q *Queries) GetUtxosByAddress(ctx context.Context, address string) ([]Utxo, error) {
	rows, err := q.db.Query(ctx, getUtxosByAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Utxo
	for rows.Next() {
		var i Utxo
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Address,
			&i.Value,
			&i.ScriptPubKeyHex,
			&i.Coinbase,
			&i.BlockHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUtxo = `-- name: InsertUtxo :exec
INSERT INTO utxos (txid, vout, address, value, script_pub_key_hex, coinbase, block_height)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (txid, vout) DO NOTHING
`

type InsertUtxoParams struct {
	Txid            string
	Vout            int64
	Address         string
	Value           int64
	ScriptPubKeyHex string
	Coinbase        bool
	BlockHeight     int64
}

func (q *Queries) InsertUtxo(ctx context.Context, arg InsertUtxoParams) error {
	_, err := q.db.Exec(ctx, insertUtxo,
		arg.Txid,
		arg.Vout,
		arg.Address,
		arg.Value,
		arg.ScriptPubKeyHex,
		arg.Coinbase,
		arg.BlockHeight,
	)
	return err
}
