// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vins.sql

package repository

import (
	"context"
)

const deleteVinsByTxid = `-- name: DeleteVinsByTxid :exec
DELETE FROM vins WHERE txid = $1
`

func (q *Queries) DeleteVinsByTxid(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteVinsByTxid, txid)
	return err
}

const getVinsByTxid = `-- name: GetVinsByTxid :many
SELECT id, txid, vout, coinbase, prev_txid, prev_vout, script_sig, sequence, txinwitness FROM vins WHERE txid = $1 ORDER BY id
`

func (q *Queries) GetVinsByTxid(ctx context.Context, txid string) ([]Vin, error) {
	rows, err := q.db.Query(ctx, getVinsByTxid, txid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vin
	for rows.Next() {
		var i Vin
		if err := rows.Scan(
			&i.ID,
			&i.Txid,
			&i.Vout,
			&i.Coinbase,
			&i.PrevTxid,
			&i.PrevVout,
			&i.ScriptSig,
			&i.Sequence,
			&i.Txinwitness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVin = `-- name: InsertVin :exec
INSERT INTO vins (txid, vout, coinbase, prev_txid, prev_vout, script_sig, sequence, txinwitness)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertVinParams struct {
	Txid        string
	Vout        int64
	Coinbase    string
	PrevTxid    string
	PrevVout    int64
	ScriptSig   string
	Sequence    int64
	Txinwitness []string
}

func (q *Queries) InsertVin(ctx context.Context, arg InsertVinParams) error {
	_, err := q.db.Exec(ctx, insertVin,
		arg.Txid,
		arg.Vout,
		arg.Coinbase,
		arg.PrevTxid,
		arg.PrevVout,
		arg.ScriptSig,
		arg.Sequence,
		arg.Txinwitness,
	)
	return err
}
