// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vouts.sql

package repository

import (
	"context"
)

const deleteVoutsByTxid = `-- name: DeleteVoutsByTxid :exec
DELETE FROM vouts WHERE txid = $1
`

func (q *Queries) DeleteVoutsByTxid(ctx context.Context, txid string) error {
	_, err := q.db.Exec(ctx, deleteVoutsByTxid, txid)
	return err
}

const getVoutsByTxid = `-- name: GetVoutsByTxid :many
SELECT id, txid, n, value, script_pub_key_hex, script_pub_key_type, addresses FROM vouts WHERE txid = $1 ORDER BY n
`

func (q *Queries) GetVoutsByTxid(ctx context.Context, txid string) ([]Vout, error) {
	rows, err := q.db.Query(ctx, getVoutsByTxid, txid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vout
	for rows.Next() {
		var i Vout
		if err := rows.Scan(
			&i.ID,
			&i.Txid,
			&i.N,
			&i.Value,
			&i.ScriptPubKeyHex,
			&i.ScriptPubKeyType,
			&i.Addresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVout = `-- name: InsertVout :exec
INSERT INTO vouts (txid, n, value, script_pub_key_hex, script_pub_key_type, addresses)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVoutParams struct {
	Txid             string
	N                int64
	Value            int64
	ScriptPubKeyHex  string
	ScriptPubKeyType string
	Addresses        []string
}

func (q *Queries) InsertVout(ctx context.Context, arg InsertVoutParams) error {
	_, err := q.db.Exec(ctx, insertVout,
		arg.Txid,
		arg.N,
		arg.Value,
		arg.ScriptPubKeyHex,
		arg.ScriptPubKeyType,
		arg.Addresses,
	)
	return err
}
